dev: initial push for inventory plugin
openstack-k8s-operators/ansibleee-operator pull request #1
Opened 2022-09-19 15:20 UTC by cloudguruab

- Wrote a small method that will check whether a filepath is empty, and also parse a filepath for contents which are loaded into an array. We can use this to write the configuration of the inventory source into a `inventory.yaml` file so we dont have to change any of the other code. This is a preliminary PR as I think i'll need time when you're available to sync & pair hack on this if you'd like!

2022-09-21 07:22 UTC, jlarriba requested changes

2022-09-28 16:13 UTC, cloudguruab commented on controllers/ansibleee_controller.go
> +func CheckEmpty(name string) (bool, error) {
No use outside the file, changed the CheckEmpty to `checkEmpty` also working on module to include custom lookup plugin to build inventory dynamically github.com/cloudguruab/goggle. Going to swap out some code inside the if conditional of `checkInventorySource` method to run this module. At that point we can start merging those updates into the controllers reconcile function and any other place we use iteration to grab host information or would need to use lookups.

2022-09-28 16:14 UTC, cloudguruab commented on controllers/ansibleee_controller.go
> +func CheckEmpty(name string) (bool, error) {
Also, I see `configMap` has been swapped out in some places from whats setup on initial build from operatorSDK whats this pulled from? is configMap a naming convention or resource used outside this operator anywhere?

2022-09-29 12:16 UTC, jlarriba commented on controllers/ansibleee_controller.go
> +func CheckEmpty(name string) (bool, error) {
The operator creates a configMap object to store the yaml inventory provided by the user. ConfigMaps in kubernetes are key-value stores, and they are very useful to store yaml information, such as the inventory.

2022-10-18 21:22 UTC, closed without merging