Rename ansibleee-operator to openstack-ansibleee-operator
openstack-k8s-operators/ansibleee-operator pull request #50
Opened 2023-01-13 16:54 UTC by fao89

closes [OSP-21337](https://issues.redhat.com/browse/OSP-21337)

Signed-off-by: Fabricio Aguiar <fabricio.aguiar@gmail.com>

2023-01-13 17:25 UTC, fmount approved these changes

2023-01-16 09:30 UTC, jlarriba requested changes
Just a small nitpick.

2023-01-16 09:30 UTC, jlarriba commented on config/manifests/bases/openstack-ansibleee-operator.clusterserviceversion.yaml
> +      displayName: Open Stack Ansible EE
typo: OpenStack, without space

2023-01-16 10:44 UTC, jlarriba approved these changes

2023-01-16 10:46 UTC, merged